# Base prototypes can be found in \Resources\Prototypes\Recipes\Lathes\security.yml
#region Base
- type: latheRecipe
  id: BaseEmptyMagazineRecipe
  abstract: true
  categories:
  - NFMagazines
  completetime: 1

- type: latheRecipe
  id: BaseFilledMagazineRecipe
  parent: BaseEmptyMagazineRecipe
  abstract: true
  completetime: 2.5

#region Xbow Bolts
- type: latheRecipe # crossbow bolt
  id: CrossbowBolt
  parent: BaseAmmoRecipe
  result: CrossbowBolt
  materials:
    Steel: 20

- type: latheRecipe # crossbow bolt
  id: CrossbowBoltBroadhead
  parent: BaseAmmoRecipe
  result: CrossbowBoltBroadhead
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponPistolPollock
  result: WeaponPistolPollock
  completetime: 3
  materials:
    Steel: 1000
    Plastic: 1200
    Plasteel: 1200
    
- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyRifleSniperCannon
  result: NFWeaponEnergyRifleSniperCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

# region Misc
- type: latheRecipe
  id: ClothingEyesHudNfsd
  parent: ClothingEyesHudSecurity
  result: ClothingEyesHudNfsd

- type: latheRecipe
  id: HoloprojectorNfsd
  parent: ClothingEyesHudSecurity
  result: HoloprojectorNfsdEmpty

# region Upstream Removed
- type: latheRecipe
  parent: Handcuffs
  id: NFHandcuffs

- type: latheRecipe
  parent: Zipties
  id: NFZipties

- type: latheRecipe
  parent: Stunbaton
  id: NFStunbaton

- type: latheRecipe
  parent: Truncheon
  id: NFTruncheon

- type: latheRecipe
  parent: CombatKnife
  id: NFCombatKnife

- type: latheRecipe
  parent: ClothingBackpackElectropack
  id: NFClothingBackpackElectropack

- type: latheRecipe
  parent: ForensicPad
  id: NFForensicPad

- type: latheRecipe
  parent: ClothingEyesHudSecurity
  id: NFClothingEyesHudSecurity

- type: latheRecipe
  parent: HoloprojectorSecurity
  id: NFHoloprojectorSecurityEmpty

- type: latheRecipe
  parent: RiotShield
  id: NFRiotShield

- type: latheRecipe
  parent: TelescopicShield
  id: NFTelescopicShield

- type: latheRecipe
  parent: Flash
  id: NFFlash

- type: latheRecipe
  id: NFTargetHuman
  result: TargetHuman

- type: latheRecipe
  parent: TargetClown
  id: NFTargetClown

- type: latheRecipe
  parent: TargetSyndicate
  id: NFTargetSyndicate

- type: latheRecipe
  id: NFPortableRecharger
  parent: PortableRecharger
