- type: job
  id: CentComNavyman
  name: job-name-naval
  description: job-description-naval
  playTimeTracker: JobCentComNavyman
  setPreference: false
  startingGear: CentComNavymanGear
  icon: "JobIconCentCom"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - Naval
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentComNavymanGear
  equipment:
    jumpsuit: ClothingUniformCentComNavy
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSunglasses
    belt: ClothingBeltAssault
    gloves: ClothingHandsGlovesCombat
    id: NavalPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: WeaponPistolMk58
    pocket2: Magazine45_ACPPistolHighCapacityFMJ
