- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconCentCom"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  #- NanotrasenRepresentative # We dont have that
  #- BlueshieldOfficer # We dont have that
  special:  # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Executive Access!
    eyes: ClothingEyesGlassesMedSec # Better glasses
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    id: CBURNPDA
    pocket1: InfectionScannerCburn # Goob
    pocket2: NFWeaponEnergyPistolLaser # Frontier: WeaponLaserGun<NFWeaponEnergyPistolLaser
    belt: ClothingBeltBandolierIncendiary # Sandwich-HL: If anyone ever removes this, please also delete the entity in shotguns.yml
  storage:
    back:
    - WeaponShotgunEnforcerIncendiary # CBURN desperately needs a good fucking gun, not that dogshit (double barreled). [If anyone ever removes this, please also delete the entity in shotguns.yml]
    - AmmoBox12_gaugeIncendiary
    - AmbuzolPlusMedipen # Injectors are cooler.
    - AmbuzolMedipen # Injectors are cooler.
    - AmbuzolMedipen # Injectors are cooler.
    - MedkitCombatFilled # Ah yes, let's send them in with ZERO meds. Good luck
    - RadioHandheldNF # Frontier: RadioHandheld<RadioHandheldNF
    - CburnSpear # SPEAAR
