# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconCentCom"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]
  whitelisted: true # Frontier

- type: startingGear
  id: ERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTLeader
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Sandwich-HL
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives". Is never used anywhere else.
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
    - ERTSecurityUndeterminedWeapon
    #- Magazine45_magnumPistolFMJ - No need

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Sandwich-HL
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives". Is never used anywhere else.
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - BoxZiptie
    - MedkitCombatFilled # Goobstation - No reason not to.
    - CrowbarRed
    - ERTSecurityUndeterminedWeapon
    #- Magazine45_magnumPistolFMJ - No need

- type: startingGear
  id: ERTLeaderGearEVALecter
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Sandwich-HL
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives". Is never used anywhere else.
    pocket2: Magazine762x39mmFMJ
  inhand:
  - WeaponRifleAnnie # Annie cooler than Lecter
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - BoxZiptie
    - MedkitCombatFilled # Goobstation - No reason not to.
    - CrowbarRed
    - Magazine762x39mmFMJ
    - Magazine762x39mmFMJ

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  - !type:AddImplantSpecial
     implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]
  whitelisted: true # Frontier

- type: startingGear
  id: ERTChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHatFez
    eyes: ClothingEyesGlasses
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltHolsterFilledBlessed # Holy weapon... (well, almost)
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: DrinkWaterBottleFull
  storage:
    back:
    - BoxCandle
    - BoxBodyBag
    # - DrinkWaterMelonJuiceJug # Why...
    - Lantern
    - Lantern
    - Bible
    - CrowbarRed
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FlippoEngravedLighter # Sandwich-HL - this is better
    - ExecutiveIDCard # Goobstation - Executive Access!

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlasses
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltHolsterFilledBlessed # Holy weapon... (well, almost)
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: DrinkWaterBottleFull
  storage:
    back:
    - BoxCandle
    - BoxBodyBag
    # - DrinkWaterMelonJuiceJug # Why...
    - Lantern
    - Lantern
    - Bible
    - CrowbarRed
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FlippoEngravedLighter # Sandwich-HL - this is better
    - ExecutiveIDCard # Goobstation - Executive Access!

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]
  whitelisted: true # Frontier

- type: startingGear
  id: ERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTEngineer
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: AirGrenade # Ah yes, put a gas analyuer in their pocket altough its in the CE belt
  storage:
    back:
    - RCD
    - RCDAmmo
    - RCDAmmo
    - AirGrenade
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass
    - BoxDispenserFlare # Sandwich-HL
    - NFInflatableWindowStack # Sandwich-HL
    - NFInflatableWindowStack # Sandwich-HL

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: AirGrenade # Ah yes, put a gas analyuer in their pocket altough its in the CE belt
  storage:
    back:
    - RCD
    - RCDAmmo
    - RCDAmmo
    - AirGrenade
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass
    - BoxDispenserFlare # Sandwich-HL
    - NFInflatableWindowStack # Sandwich-HL
    - NFInflatableWindowStack # Sandwich-HL

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm]
  whitelisted: true # Frontier

- type: startingGear
  id: ERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTSecurity
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - BoxZiptie
    - MedkitCombatFilled # Goobstation - No reason not to.
    - CrowbarRed
    - ERTSecurityUndeterminedWeapon

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - BoxZiptie
    - MedkitCombatFilled # Goobstation - No reason not to.
    - CrowbarRed
    - ERTSecurityUndeterminedWeapon
    # - Magazine9x19mmPistolFMJ

- type: startingGear
  id: ERTSecurityGearEVALecter
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: Magazine762x39mmFMJ
  inhand:
    - WeaponRifleAnnie # Annie cooler than Lecter
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - BoxZiptie
    - MedkitCombatFilled # Goobstation - No reason not to.
    - CrowbarRed
    - Magazine762x39mmFMJ
    - Magazine762x39mmFMJ

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]
  whitelisted: true # Frontier

- type: startingGear
  id: ERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTMedic
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Goobstation
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbingFilledMedical # Fancier
    pocket1: Flare
    pocket2: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives"
  storage:
    back:
    - CentCommHypo
    - MedkitAdvancedFilled # Goobstation
    - CrowbarRed
    - ChemistryBottleOmnizine
    - JugOxandrolone # Goobstation
    - JugSalicylicAcid # Goobstation
    - ParamedHypo # Goobstation
    - CartridgeAtropine
    - CartridgeAtropine
    #- MedicalBeamGunBattery  # I certainly wont port this

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Goobstation
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbingFilledMedical # Fancier
    pocket1: Flare
    pocket2: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives"
  storage:
    back:
    - CentCommHypo
    - MedkitAdvancedFilled # Goobstation
    - CrowbarRed
    - ChemistryBottleOmnizine
    - JugOxandrolone # Goobstation
    - JugSalicylicAcid # Goobstation
    - ParamedHypo # Goobstation
    - CartridgeAtropine
    - CartridgeAtropine
    #- MedicalBeamGunBattery  # I certainly wont port this

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial # Goobstation
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm]
  whitelisted: true # Frontier

- type: startingGear
  id: ERTJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTJanitor
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
    pocket1: Flare
    pocket2: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
  storage:
    back:
    - BoxLightMixed
    - BoxLightMixed
    - LightReplacer
    - Soap
    - CrowbarRed
    - AdvMopItem

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
    pocket1: Flare
    pocket2: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
  storage:
    back:
    - BoxLightMixed
    - BoxLightMixed
    - LightReplacer
    - Soap
    - CrowbarRed
    - AdvMopItem
